# Generated by Django 4.1.1 on 2022-09-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lugat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=30, verbose_name="english")),
                ("uzbek", models.CharField(max_length=30, verbose_name="uzbek")),
            ],
        ),
    ]
